name: io_axrs_dart_cli_tools

dependencies:
  barbecue: ^0.4.0
  build_runner: ^1.12.0
  collection: ^1.15.0
  colorize: ^3.0.0
  duration: ^3.0.6
  fpdart: ^0.0.11
  get_it: ^7.2.0
  reflectable: ^3.0.0
  smart_arg:
    git: https://github.com/axrs/smart_arg.git

environment:
  sdk: '>=2.10.0 <3.0.0'
